config/routes.rb
GoBabyGo::Application.routes.draw do
  match '/signup', to: 'parents#new', via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  resources :sessions, only: [:new, :create, :destroy]
  resources :parents do
    resources :kids, shallow: true
  end
  resources :kids do
    resources :firsts, shallow: true
  end

  get 'about', to: 'home#about'

  root 'home#index'

end

app/models/first.rb
class First < ActiveRecord::Base
  belongs_to :kid
end

app/models/kid.rb
class Kid < ActiveRecord::Base
  belongs_to :parent
  has_many :firsts, dependent: :destroy
  validates :parent_id, presence: true
end

app/models/parent.rb
class Parent < ActiveRecord::Base
  has_many :kids

  before_save { self.email = email.downcase }
  before_create :create_remember_token

  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, length: { minimum: 6 }


  def Parent.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def Parent.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = Parent.encrypt(Parent.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/firsts_controller.rb
class FirstsController < ApplicationController
  def index
    @kid = Kid.find_by_id(params[:kid_id])
    @firsts = First.where("kid_id = ?", @kid.id)
  end

  def new
    @first = First.new
    @kid = Kid.find_by_id(params[:kid_id])
  end

  def create
    @first = First.new(firsts_params)
    @first.update_attributes(kid_id: params[:kid_id])

    if @first.save
      flash[:success] = "Baby....created!"
      redirect_to @first
    else
      redirect_to 'new'
    end
  end

  def show
    @first = First.find(params[:id])
  end

  private

  def firsts_params
    params.require(:first).permit(:occurred_at,
      :description)
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/kids_controller.rb
class KidsController < ApplicationController
  def index
    @kids = Kid.where("parent_id = ?", params["parent_id"])
  end

  def new
    @kid = Kid.new
  end

  def create
    @kid = Kid.new(kids_params)
    @kid.update_attributes(parent: current_parent)
    if @kid.save
      flash[:success] = "Baby....created!"
      redirect_to @kid
    else
      redirect_to 'new'
    end
  end

  def show
    @kid = Kid.find(params[:id])
  end

  private

  def kids_params
    params.require(:kid).permit(:name,
      :birthdate, :birthplace, :weight, :height)
  end

end

app/controllers/parents_controller.rb
class ParentsController < ApplicationController
  before_action :signed_in_parent, only: [:edit, :update]
  before_action :correct_parent,   only: [:edit, :update]

  def new
    @parent = Parent.new
    render layout: "no_header_footer"
  end

  def show
    @parent = Parent.find(params[:id])
  end

  def create
    @parent = Parent.new(parent_params)
    if @parent.save
      sign_in @parent
      flash[:success] = "Welcome to Go Baby, Go!"
      redirect_to @parent
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @parent.update_attributes(parent_params)
      flash[:success] = "Profile updated"
      sign_in @parent
      redirect_to @parent
    else
      render 'edit'
    end
  end

  private

  def parent_params
    params.require(:parent).permit(:name, :email, :password,
                                   :password_confirmation)
  end

  def signed_in_parent
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def correct_parent
    @parent = Parent.find(params[:id])
    redirect_to(root_url) unless current_parent?(@parent)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render layout: "no_header_footer"
  end

  def create
     parent = Parent.find_by(email: params[:session][:email].downcase)
    if parent && parent.authenticate(params[:session][:password])
      sign_in parent
      redirect_back_or parent
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/firsts_helper.rb
module FirstsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(parent)
    remember_token = Parent.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    parent.update_attribute(:remember_token, Parent.encrypt(remember_token))
    self
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def signed_in?
    !current_parent.nil?
  end

  def current_user=(parent)
    @current_parent = parent
  end

  def current_parent
    remember_token = Parent.encrypt(cookies[:remember_token])
    @current_parent ||= Parent.find_by(remember_token: remember_token)
  end

  def current_parent?(parent)
    parent == current_parent
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end
end

app/views/firsts/index.html.erb
<header id="introduction">
  <div class="container">
    <div class="col col-md-6 col-md-offset-3">
      <h1>Firsts for: <%= @kid.name %></h1>
    </div>
</div>
</header>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <ul> Please select a first:
      <% @firsts.each do |first| %>
      <li><%= link_to(first.description, first_path(id: first.id)) %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/firsts/new.html.erb
<header id="introduction">
  <div class="container">
    <h1>Go Baby, Go!</h1>
    <h4>Enter information about what just happened.</h4>
  </div>
</header>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for([@kid, @first]) do |f| %>
    <%= f.text_field :description, class: "form-control", placeholder: "First description" %>
    <%= f.text_field :occurred_at, class: "form-control", placeholder: "Date Occurred" %>
    <p>
      <%= f.submit "Add", class: "btn btn-large btn-primary" %>
    </p>
    <% end %>
  </div>
</div>

app/views/firsts/show.html.erb
<header id="introduction">
  <div class="container">
    <h1><%= @first.description %> </h1>
  </div>
</header>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <p>Description:<%= @first.description %></p>
    <p>Occurred At: <%= @first.occurred_at %></p>
  </div>
</div>

app/views/home/about.html.erb
<header id="introduction">
  <div class="container">
    <h1>Where'd we get this idea?</h1>
    <h4>Wouldn't you like to know...</h4>
  </div>
</header>
<section id="why">
  <div class="container">
    <div class="col col-md-6 col-md-offset-3">
      <p>
        My wife and I had our second child in 2012,
        and we had purchased a baby book to document his
        first years of life - kind of like we did with
        our first child.  On his first birthday, we pulled
        out his baby book and found all but the first couple
        pages blank.
      </p>
      <p>
        Great!  How are we going to fill this out now?  We
        can't possibly remember what day each of the items
        in our baby book is asking for.  Poor kid, I hope
        he doesn't feel slighted when he gets old enough to
        read this.
      </p>
      <p>
        So, it's 2013 and our third child is due in September
        (yes, I know what you are thinking; two years, two kids.
        It happens!) My wife and I were sitting around trying to think of
        ideas on how we can keep track of all of our new baby's
        memories, and came up with this. Go, Baby! Go!
      </p>
    </div>
  </div>
</section>

app/views/home/index.html.erb
<header id="introduction">
  <div class="container">
    <h1>Capture baby's first experiences</h1>
    <h4>Your baby only does something for the first time once.  Don't miss it.</h4>
    <%= link_to "SIGN UP NOW!", signup_path, class: "btn btn-warning" %>
  </div>
</header>
<section id="features">
  <div class="container">
    <div class="row">
      <div class="col-md-7">
        <h2 class='feature-heading'>Baby book, shmaby book</h2>
        <p class="lead">
          The days of forgetting to write stuff in your precious
          son's or daughter's baby book are gone!  Capture moments
          as they happen! Soon, you'll have more kids and you
          can now fight the urge to buy them a baby book to only have
          it sit around anyway.  Poor kid - their older sibling has all
          these memories and you've somehow forgotten to add their latest
          coo to the new baby book.
        </p>
        <p class="lead">Go Baby Go! has your back.</p>
      </div>
      <div class="col-md-5">
        <img class="img-responsive" src="#" data-src="holder.js/500x500/auto" alt="placeholder">
      </div>
    </div>
    <hr class='feature-divider'>
    <div class='row'>
      <div class="col-md-5">
        <img class="img-responsive" src="#" data-src="holder.js/500x500/auto" alt="placeholder">
      </div>
      <div class="col-md-7">
        <h2 class='feature-heading'>Available everywhere</h2>
        <p class="lead">
         Capture your princess rolling over, or junior's first tooth on
         your closest device.  No need to grab that pen (or just forget totally).
       </p>
      </div>
    </div>
   <hr class='feature-divider'>
   <div class="row">
     <div class="col-md-7">
       <h2 class='feature-heading'>Hey, can your baby book do this?</h2>
       <p class="lead">
         Did I mention you can take photos? Oh yeah - capture your little one
         in action by snapping a quick photo.  It'll be forever documented,
         waiting for you to print it out and put it on a photo board to embarrass
         them at their graduation party.
       </p>
      </div>
      <div class="col-md-5">
        <img class="img-responsive" src="#" data-src="holder.js/500x500/auto" alt="placeholder">
      </div>
    </div>
  </div>
</section>

app/views/kids/index.html.erb
<header id="introduction">
  <div class="container">
    <div class="col col-md-6 col-md-offset-3">
      <h1>My Kids</h1>
    </div>
</div>
</header>

<div class="row">
  <div id="kids-list" class="col-md-6 col-md-offset-3">
    <ul> Please select a child:
      <% @kids.each do |kid| %>
      <li><%= link_to(kid.name, kid_path(id: kid.id)) %></li>
      <% end %>
    </ul>
    <h5>(Note: Go Baby Go! cannot make any <em>real</em> changes to your kids though!)</h5>
  </div>
</div>

app/views/kids/new.html.erb
<header id="introduction">
  <div class="container">
    <h1>Congratulations!</h1>
    <h4>Enter information about your new bundle of joy!</h4>
  </div>
</header>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@kid) do |f| %>
    <%= f.text_field :name, class: "form-control", placeholder: "Baby's name" %>
    <%= f.text_field :birthdate, class: "form-control", placeholder: "Birthdate" %>
    <%= f.text_field :birthplace, class: "form-control", placeholder: "Place of birth" %>
    <%= f.text_field :weight, class: "form-control", placeholder: "Birth weight" %>
    <%= f.text_field :height, class: "form-control", placeholder: "Length" %>
    <p>
      <%= f.submit "Add", class: "btn btn-large btn-primary" %>
    </p>
    <% end %>
  </div>
</div>

app/views/kids/show.html.erb
<header id="introduction">
  <div class="container">
    <h1><%= @kid.name %> </h1>
  </div>
</header>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <p>Birthday:<%= @kid.birthdate %></p>
    <p>Birthplace: <%= @kid.birthplace %> </p>
    <p>Birth weight: <%= @kid.weight %> </p>
    <p>Birth height: <%= @kid.height %> </p>
    <p> <%= button_to "Add a first", new_kid_first_path(kid_id: @kid.id), method: :get, class: "btn btn-large btn-primary" %></p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>GoBabyGo</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
  </head>

  <body style>
    <div id="wrap">
    <%= render 'shared/navigation' %>
    <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
    <% end %>
    <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/layouts/no_header_footer.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>GoBabyGo</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
  </head>

  <body id="no-header-footer" style>
    <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
    <% if Rails.env.test? %>
    <div class="container">
      <%= debug(params) %>
    </div>
    <% end %>
  </body>
</html>

app/views/parents/edit.html.erb
<header id="introduction">
  <div class="container">
    <h1>Update your profile</h1>
  </div>
</header>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@parent) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

  </div>
</div>

app/views/parents/new.html.erb
<div class="container">

  <%= form_for(@parent, html: { class: "form-signin"}) do |f| %>
  <h2>Sign up</h2>
  <%= render 'shared/error_messages' %>

  <%= f.text_field :name, class: "form-control", placeholder: "Name" %>

  <%= f.text_field :email, class: "form-control", placeholder: "Email" %>

  <%= f.password_field :password, class: "form-control", placeholder: "Password" %>

  <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Password confirmation" %>

  <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
  <% end %>
</div>

app/views/parents/show.html.erb
<div class="container">
  <h2>Hello, <%= @parent.name %>!</h2>
  <p>Please choose an option:</p>
  <p><%= link_to "Having a new child?", new_parent_kid_path(parent_id: @parent.id) %> </p>
  <% if @parent.kids.length > 0 %>
  <p><%= link_to "Take me to my kids!", parent_kids_path(parent_id: @parent.id) %></p>
  <% end %>
</div>

app/views/shared/_error_messages.html.erb
<% if @parent.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@parent.errors.count, "error") %>.
    </div>
    <ul>
    <% @parent.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="container">
    <div class='row'>
      <div class='col-lg-12'></div>
      <p class="text-muted credit">&copy; 2012 | Vidality </p>
    </div>
  </div>
</footer>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-static-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Go Baby, Go!", root_path, id: "logo", class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav pull-right">
        <li><%= link_to "ABOUT", about_path %></li>
        <li class="sep"></li>
        <% if signed_in? %>
        <li><%= link_to "Users", '#' %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Profile", current_parent %></li>
            <li><%= link_to "Settings", edit_parent_path(current_parent) %></li>
            <li>
              <%= link_to "Sign out", signout_path, method: "delete" %>
            </li>
          </ul>
        </li>
        <% else %>
        <li><%= link_to "LOG IN", signin_path %></li>
        <li><%= link_to "SIGN UP", signup_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>